#!/bin/sh

set -e

which -s brew || (echo "Homebrew is required: http://brew.sh/" && exit 1)

brew bundle check || brew bundle

# Prepare custom settings for Karabiner-Elements
# https://github.com/tekezo/Karabiner-Elements/issues/597#issuecomment-282760186
mkdir -p ~/.config
ln -sfn $PWD/karabiner ~/.config/

# Prepare custom settings for Hammerspoon
mkdir -p ~/.hammerspoon
if ! grep -sq "require('keyboard')" ~/.hammerspoon/init.lua; then
  echo "require('keyboard') -- Load Hammerspoon bits from https://github.com/jasonrudolph/keyboard" >> ~/.hammerspoon/init.lua
fi
ln -sfn $PWD/hammerspoon ~/.hammerspoon

# Prepare custom settings for navigating between words in iTerm2
grep -sq forward-word ~/.inputrc || cat $PWD/inputrc >> ~/.inputrc

# Disable Dock icon for Hammerspoon
defaults write org.hammerspoon.Hammerspoon MJShowDockIconKey -bool FALSE

# If Hammerspoon is already running, kill it so we can pick up the new config
# when opening Hammerspoon below
killall Hammerspoon || true

# Open Apps
open /Applications/Hammerspoon.app
open /Applications/Karabiner-Elements.app

# Enable apps at startup
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Hammerspoon.app", hidden:true}' > /dev/null
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Karabiner-Elements.app", hidden:true}' > /dev/null

echo "Done! Remember to enable Accessibility for Hammerspoon."



#  触控板单点。
#  键盘  快捷键 屏幕快照  置换34
#  缩放效果
#  辅助功能 鼠标与触控板  触控板选项 拖移
#  辅助功能 显示 减弱动态效果。提高对比度
#  辅助中的语音 Tom mei-jia. Sam
#
#
#
#  rm -rf ~/.config/karabiner
#  ln -sfn $PWD/karabiner ~/.config/
#
#  ln -sfn $PWD/hammerspoon ~/.hammerspoon


#  Brew brew
#
#  安装python3 安装requests库
#  安装node 和 库   npm install  @vitalets/google-translate-api
#
#  Bash setup.sh
#
#  man中文  https://xujiazhe.github.io/work/2017/11/01/macos-doc-chinese.html
#
#  https://github.com/robbyrussell/oh-my-zsh
#  https://github.com/amix/vimrc
#
#  safari设置样式表
#
#  tb3
#    https://github.com/rgov/Thunderbolt3Unblocker/releases
#
#  proxychains-ng    https://github.com/haad/proxychains

# https://github.com/kuoruan/shell-scripts
# https://ssr.tools/588  一装就挂
