#!/bin/sh

set -e
# 文件  Brewfile  brew.sh    更换源 https://www.cnblogs.com/zunwen/p/12597654.html
which -s brew || (echo "Homebrew is required: http://brew.sh/" && exit 1)
brew bundle check || brew bundle
# APPStore "Be Focused"

触控板单点。
程序坞。最小化。缩放效果。
键盘 
	键盘 F1 F2 
	文本 拼写
	快捷键
		显示桌面
		输入法 上一个下一个 ^.
		屏幕快照  置换34
		聚焦
	输入法   简体双拼 微软
	听写 可用了

辅助功能 
	鼠标与触控板  触控板选项 拖移
	显示 减弱动态效果。提高对比度
	语音 Tom mei-jia  Sam    稍后 精度提高



# 安装了两个软件之后，不用启动，在 dotfiles 中
#  rm -rf ~/.config/karabiner
#  ls ~/.config || mkdir ~/.config
#  ln -sfn $PWD/karabiner ~/.config/

#  ln -sfn $PWD/hammerspoon ~/.hammerspoon

#  校验 # 打开设置 参见 setup.sh
# https://github.com/asmagill/hs._asm.axuielement
#  bash setup.sh

set -e

#https://www.zhihu.com/question/31360766

which -s brew || (echo "Homebrew is required: http://brew.sh/" && exit 1)
brew bundle check || brew bundle

# Prepare custom settings for Karabiner-Elements
# https://github.com/tekezo/Karabiner-Elements/issues/597#issuecomment-282760186
mkdir -p ~/.config
ln -sfn $PWD/karabiner ~/.config/

# Prepare custom settings for Hammerspoon
mkdir -p ~/.hammerspoon
if ! grep -sq "require('keyboard')" ~/.hammerspoon/init.lua; then
  echo "require('keyboard') -- Load Hammerspoon bits from https://github.com/jasonrudolph/keyboard" >> ~/.hammerspoon/init.lua
fi
ln -sfn $PWD/hammerspoon ~/.hammerspoon


# Disable Dock icon for Hammerspoon
defaults write org.hammerspoon.Hammerspoon MJShowDockIconKey -bool FALSE

# If Hammerspoon is already running, kill it so we can pick up the new config
# when opening Hammerspoon below
killall Hammerspoon || true

# Open Apps
open /Applications/Hammerspoon.app
open /Applications/Karabiner-Elements.app

# Enable apps at startup
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Hammerspoon.app", hidden:true}' > /dev/null
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Karabiner-Elements.app", hidden:true}' > /dev/null

echo "Done! Remember to enable Accessibility for Hammerspoon."


# Brew brew
# brew install autossh wget openssh
# brew install python3 pip3 node npm
# npm install @vitalets/google-translate-api
# /usr/local/opt/python@3.9/libexec/bin/pip install requests
# X  pip3 install requests

#  Bash setup.sh
#
#  man中文  https://xujiazhe.github.io/work/2017/11/01/macos-doc-chinese.html
#
#  https://github.com/robbyrussell/oh-my-zsh
#  https://github.com/amix/vimrc
#
#  safari设置样式表
#
#  tb3
#    https://github.com/rgov/Thunderbolt3Unblocker/releases

# https://github.com/kuoruan/shell-scripts
# https://ssr.tools/588  一装就挂


# Prepare custom settings for navigating between words in iTerm2
grep -sq forward-word ~/.inputrc || cat $PWD/inputrc >> ~/.inputrc


#ID   https://icpc.baylor.edu/ICPCID/TJIWVK522BOO
#https://www.linkedin.com/in/jiazhe-xu-03545548/

